### PR TITLE
Picked up github actions

### PR DESCRIPTION
**Pull request by klimburg**
@vmalloc I got the unit tests working in github. 

I had to pin back some versions and also make the `SQLALCHEMY_DATABASE_URI` more explicit in `app.yml` and finally use the [bitnami postgres container image](https://hub.docker.com/r/bitnami/postgresql/) so i could disable fsync. Unit test run times went from over an hour to a couple of minutes when i did that.

### CODE REVIEW

**Comment by vmalloc** [comment]
Wow! Thanks a lot for picking this up. I started with it but got overrun with other stuff. Really appreciate your help with this one!

**Comment by klimburg** [comment]
No problem! I am expecting to be putting some more time into backslash over the next couple weeks as there are a few features I want to implement, namely microsoft sso integration and a way to export a static report (pdf probably?), so I wanted to make sure I was on a stable footing. 

I'll write up issues for the features I'm interested in doing once I have had some time to play around with them a bit. I'll also get a PR up for fixing #641 today or tomorrow.

**Comment by vmalloc** [comment]
Not all heroes wear capes ;-)

**Comment by klimburg** [comment]
What’s your preference for getting this merged? It doesn’t look like the actions will run on this branch. Do you want me to open a pr into your feature/GitHub-actions branch? Or do you just want to squash and cherry-pick them onto your branch? Let me know.

**Comment by vmalloc** [comment]
I think you can squash them into a PR into Github-actions - I'm pretty sure the actions run from there. If for some reason they don't, we can merge to develop and work from there

**Comment by klimburg** [comment]
@vmalloc https://github.com/getslash/backslash/pull/644 to merge my changes into your branch.

**Comment by klimburg** [comment]
Closed in favor of #644

**Pull request closed without merging**
