### PR TITLE
GitHub actions continued

### PR DESCRIPTION
**Pull request by klimburg**
@vmalloc this can be merged into your branch. Let me know if you want any changes.

### CODE REVIEW

**Comment by klimburg** [comment]
Here is it passing the tests in my fork https://github.com/parallelsystems/backslash/runs/4024747561?check_suite_focus=true

**Comment by vmalloc** [comment]
@klimburg mind if I squash it all to a single commit before merging?

**Comment by klimburg** [comment]
no please do, let me know if in the future you prefer I squash on my end and force push or if you are happy to do it with the github squash and merge feature. I know force pushing will screw up some of the nice github features like the ability to review all changes since last review and sometimes break links to comments (not relevant here) so I typically just set my repos up for "squash and merge"

**Comment by vmalloc** [comment]
@klimburg Thank you very very much! I merged it, and will follow the actions execution to make sure it completes. Once it does I'll merge to develop.

Your contribution is greatly appreciated!

**Pull request merged**
